### ISSUE TITLE
save analysis files

### ISSUE THREAD

**Issue by tgerke** [GerkeLab/PAM50#2]
The cleanup script is useful (I don't want to keep the initial .tar either!). Not ideal to redownload the whole thing each time though; would it be possible to save the small analysis file with the non-duplicative pData() columns + the 50 genes + the output from the PAM50 algorithm (each version separately; i.e. reassigning/not reassigning HER2 etc)?

**Comment by gadenbuie** [comment]
Sounds good! There are checkpoint outputs in the scripts that I can add with a little modification for easy use with GitHub.

The gather data script is a one-time thing but it does go out and pull in 12gb+ (i.e. once the data is in the right place the script skips over the download). I can make sure the source data is also in our shared drive so that part can be pulled in more quickly.
